server:
  port: 9093
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/  h2:
    console:      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: PAYMENT-SERVICE